#using Ubuntu 18.04 LTS Bionic
dist: bionic
language: cpp
before_script:
- sudo apt-get install libgtest-dev -y
- sudo apt-get install cmake -y
- pwd
- pushd /usr/src/googletest && sudo cmake . && sudo cmake --build . --target install && popd
- pwd
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    #https://www.jfrog.com/confluence/display/BT/Debian+Repositories
    #curl -T <FILE.deb> -u<USER_NAME>:<API_KEY> https://api.bintray.com/content/<USERNAME>/<REPOSITORY_NAME>/<PACKAGE_NAME>/<VERSION_NAME>/<FILE_TARGET_PATH>;deb_distribution=<DISTRIBUTIONS>;deb_component=<COMPONENTS>;deb_architecture=<ARCHITECTURES>
    #curl -T <FILE.deb> -ucpp-student-2020-vv:<API_KEY> https://api.bintray.com/content/noneid/otus-cpp-2020-deb/<YOUR_COOL_PACKAGE_NAME>/<VERSION_NAME>/<FILE_TARGET_PATH>;deb_distribution=<DISTRIBUTIONS>;deb_component=<COMPONENTS>;deb_architecture=<ARCHITECTURES>
    #curl -ucpp.student.2020.vv@gmail.com:<SECRET> -XPUT "https://noneid.jfrog.io/artifactory/otus-cpp-2020-deb/pool/<DEBIAN_PACKAGE_NAME>;deb.distribution=<DISTRIBUTION>;deb.component=<COMPONENT>;deb.architecture=<ARCHITECTURE>" -T <PATH_TO_FILE>
  - curl -T allocators-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ucpp.student.2020.vv@gmail.com:$JFROG_IO_API_KEY -XPUT "https://noneid.jfrog.io/artifactory/otus-cpp-2020-deb/pool/allocators-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb.distribution=bionic;deb.component=main;deb.architecture=amd64"
  on:
    all_branches: true
